pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: docker compose build dev
  displayName: Build image

- script: docker compose run --rm dev bash -c 'composer install && composer ci'
  displayName: Tests
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
