pool:
  vmImage: ubuntu-latest

steps:
- script: docker info
  displayName: 'Info'

- script: |
    docker-compose down
    docker-compose build --pull
  displayName: 'Build Tests'

- script: docker-compose run --rm tests56
  displayName: 'Run Tests PHP 5.6'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)

- script: docker-compose run --rm tests74
  displayName: 'Run Tests PHP 7.4'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
    # For Codeclimate:
    GIT_COMMIT_SHA: $(Build.SourceVersion)
    GIT_BRANCH: $(Build.SourceBranch)
    CC_TEST_REPORTER_ID: $(CC_TEST_REPORTER_ID)

- task: PublishTestResults@2
  displayName: 'Publish Test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/logs/*.xml'
