pool:
  vmImage: ubuntu-latest

steps:
- script: docker-compose build --build-arg PHP_VERSION=$PHP_VERSION ci && docker-compose run --rm ci
  displayName: 'Run Tests PHP 7.4'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
    PHP_VERSION: 7.4

- script: docker-compose build --build-arg PHP_VERSION=$PHP_VERSION ci && docker-compose run --rm ci
  displayName: 'Run Tests PHP 8.1'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
    PHP_VERSION: 8.1
