pool:
  vmImage: ubuntu-latest

steps:
- script: docker info
  displayName: 'Info'

- script: |
    docker-compose down
    docker-compose build --pull
  displayName: 'Build Tests'

- script: docker-compose run --rm tests74
  displayName: 'Run Tests PHP 7.4'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)

