version: "3"
services:
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile74
    environment:
      - TEST_STORAGE_API_URL
      - TEST_STORAGE_API_TOKEN
    command: ["composer", "ci"]

  dev:
    <<: *tests
    volumes:
      - ./:/code

  ci:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
    command: ["composer", "ci"]
    volumes:
      - ./build/logs/:/code/build/logs/
