services:
  ci: &ci
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_STORAGE_API_URL
      - TEST_STORAGE_API_TOKEN
    command: ["composer", "ci"]

  dev:
    <<: *ci
    volumes:
      - ./:/code
