services:
  dev:
    build:
      context: .
      args:
        PHP_VERSION: "8.2"
    environment:
      - TEST_STORAGE_API_URL
      - TEST_STORAGE_API_TOKEN
    volumes:
      - ./:/code
